### PR TITLE
Update the tools according to the change in global_state data structure in LuaJIT.

### PR DESCRIPTION
**Pull request by zhongweiy**
Now, tools like `lj-str-tab.sxx`, `lj-find-str.sxx` and `lj-gc-objs.sxx` can run correctly.

[KAG-3886]

[KAG-3886]: https://konghq.atlassian.net/browse/KAG-3886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by gszr — APPROVED** [review]

**Review by dndx — CHANGES_REQUESTED** [review]
Could you update the `README` and specify these now works just like the other tools?

**Comment by zhongweiy** [comment]
>Could you update the README and specify these now works just like the other tools?

Oops, I missed it.  It has been updated now.

**Review by gszr — APPROVED** [review]

**Comment by zhongweiy** [comment]
Ping @dndx for taking a look after my update.

**Review by dndx — APPROVED** [review]

**Comment by dndx** [comment]
@zhongweiy Updated. Could you make sure next time the ticket # is linked in the PR description as well? I have added for you this time. Thank you.

**Pull request merged**
